include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_relative_imports
    - unawaited_futures

formatter:
  page_width: 100
  trailing_commas: preserve

analyzer:
  exclude:
    - build/**
