platform :android do
  lane :deploy do
    upload_to_play_store(
      package_name: ENV["PACKAGE_NAME"],
      json_key: "android/google_auth_key.json",
      aab: "build/app/outputs/bundle/release/app-release.aab",
      mapping: "build/app/intermediates/merged_native_libs/release/out/lib/symbols.zip",
      track: "internal"
    )
  end
end

platform :ios do
  lane :deploy do
    upload_to_testflight(
      apple_id: ENV["APP_APPLE_ID"],
      app_identifier: ENV["APP_IDENTIFIER"],
      ipa: "build/ios/ipa/lolChampionRotation.ipa",
      skip_waiting_for_build_processing: true
    )
  end
end
