#!/bin/bash

set -e

echo "API_BASE_URL=$API_BASE_URL" >> .env

echo "FIREBASE_API_KEY=$FIREBASE_API_KEY" >> .env
echo "FIREBASE_APP_ID=$FIREBASE_APP_ID" >> .env
echo "FIREBASE_MESSAGING_SENDER_ID=$FIREBASE_MESSAGING_SENDER_ID" >> .env
echo "FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID" >> .env
echo "FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET" >> .env
[ -n "$FIREBASE_IOS_BUNDLE_ID" ] && echo "FIREBASE_IOS_BUNDLE_ID=$FIREBASE_IOS_BUNDLE_ID" >> .env
