name: Deploy iOS to App Store

on:
  workflow_dispatch:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  deploy-ios:
    name: Deploy to App Store
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true

      - name: Install Fastlane
        run: gem install fastlane

      - name: Setup environment
        run: |
          scripts/flutter-setup-environment.sh
          scripts/ios-setup-environment.sh
        env:
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
          CERTIFICATE_P12: ${{ secrets.IOS_CERTIFICATE_P12 }}
          PROVISIONING_PROFILE: ${{ secrets.IOS_PROVISIONING_PROFILE }}
          EXPORT_OPTIONS: ${{ secrets.IOS_EXPORT_OPTIONS }}
          FIREBASE_API_KEY: ${{ secrets.IOS_FIREBASE_API_KEY }}
          FIREBASE_APP_ID: ${{ secrets.IOS_FIREBASE_APP_ID }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_IOS_BUNDLE_ID: ${{ secrets.IOS_APP_IDENTIFIER }}

      - name: Setup signing
        run: fastlane ios setup_signing
        env:
          KEYCHAIN_PASSWORD: ${{ secrets.IOS_KEYCHAIN_PASSWORD }}
          CERTIFICATE_PASSWORD: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
          CODE_SIGN_IDENTITY: "iPhone Distribution: Tomasz Wyrowinski (SP32VN9AD9)"
          TEAM_ID: ${{ secrets.IOS_TEAM_ID }}

      - name: Build iOS app
        run: flutter build ipa --export-options-plist=ios/ExportOptions.plist

      - name: Deploy app to App Store
        run: fastlane ios deploy
        env:
          APP_APPLE_ID: ${{ secrets.IOS_APP_APPLE_ID }}
          APP_IDENTIFIER: ${{ secrets.IOS_APP_IDENTIFIER }}
          FASTLANE_USER: ${{ secrets.IOS_APPLE_USER_NAME }}
          FASTLANE_PASSWORD: ${{ secrets.IOS_APP_PASSWORD }}
