name: Deploy iOS to App Store

on:
  workflow_dispatch:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  deploy-ios:
    name: Deploy to App Store
    runs-on: macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true

      - name: Install Fastlane
        run: gem install fastlane

      - name: Setup environment
        run: |
          scripts/flutter-setup-environment.sh
          scripts/ios-setup-environment.sh
        env:
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
          CERTIFICATE_P12: ${{ secrets.IOS_CERTIFICATE_P12 }}
          PROVISIONING_PROFILE: ${{ secrets.IOS_PROVISIONING_PROFILE }}
          EXPORT_OPTIONS: ${{ secrets.IOS_EXPORT_OPTIONS }}
          FIREBASE_CONFIG: ${{ secrets.IOS_FIREBASE_CONFIG }}

      - name: Setup signing
        run: fastlane ios setup_signing
        env:
          KEYCHAIN_PASSWORD: ${{ secrets.IOS_KEYCHAIN_PASSWORD }}
          CERTIFICATE_PASSWORD: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
          CODE_SIGN_IDENTITY: ${{ secrets.IOS_CODE_SIGN_IDENTITY }}
          TEAM_ID: ${{ secrets.IOS_TEAM_ID }}

      - name: Get packages
        run: dart pub get

      - name: Generate sources
        run: dart run build_runner build

      - name: Update app identifier
        run: dart run rename setBundleId --targets ios --value ${{ secrets.IOS_APP_IDENTIFIER }}

      - name: Build iOS app
        run: flutter build ipa --export-options-plist=ios/ExportOptions.plist

      - name: Deploy app to App Store
        run: fastlane ios deploy
        env:
          APP_APPLE_ID: ${{ secrets.IOS_APP_APPLE_ID }}
          APP_IDENTIFIER: ${{ secrets.IOS_APP_IDENTIFIER }}
          FASTLANE_USER: ${{ secrets.IOS_APPLE_USER_NAME }}
          FASTLANE_PASSWORD: ${{ secrets.IOS_APP_PASSWORD }}
