name: Deploy iOS to App Store

on:
  workflow_dispatch:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  deploy-ios:
    name: Deploy to App Store
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: master
          cache: true

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true

      - name: Install Fastlane
        run: gem install fastlane

      - name: Build iOS app
        run: flutter build ipa

      - name: Deploy app to App Store
        run: fastlane ios deploy
        env:
          APP_APPLE_ID: ${{ secrets.IOS_APP_APPLE_ID }}
          APP_IDENTIFIER: ${{ secrets.IOS_APP_IDENTIFIER }}
          FASTLANE_USER: ${{ secrets.IOS_APPLE_USER_NAME }}
          FASTLANE_PASSWORD: ${{ secrets.IOS_APP_PASSWORD }}
